[package]
name = "bite-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "bite"
path = "src/main.rs"

[dependencies]
bite-schema.workspace = true
bite-expr.workspace = true
bite-core.workspace = true
bite-imagemagick.workspace = true
serde_json.workspace = true
schemars.workspace = true
ctrlc = "3.5"
